In [4]:
import pdb
import pickle
import string

import time

# import gensim
import matplotlib.pyplot as plt
import nltk
import numpy as np
import scipy
import sklearn
# from gensim.models import KeyedVectors
from nltk.corpus import stopwords, twitter_samples
from nltk.tokenize import TweetTokenizer

# from utils import (cosine_similarity, get_dict,
#                    process_tweet)
from os import getcwd

In [6]:
import re
import string

import numpy as np
import pandas as pd
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.tokenize import TweetTokenizer
import matplotlib.pyplot as plt 


def process_tweet(tweet):
    '''
    Input:
        tweet: a string containing a tweet
    Output:
        tweets_clean: a list of words containing the processed tweet

    '''
    stemmer = PorterStemmer()
    stopwords_english = stopwords.words('english')
    # remove stock market tickers like $GE
    tweet = re.sub(r'\$\w*', '', tweet)
    # remove old style retweet text "RT"
    tweet = re.sub(r'^RT[\s]+', '', tweet)
    # remove hyperlinks
    tweet = re.sub(r'https?:\/\/.*[\r\n]*', '', tweet)
    # remove hashtags
    # only removing the hash # sign from the word
    tweet = re.sub(r'#', '', tweet)
    # tokenize tweets
    tokenizer = TweetTokenizer(preserve_case=False, strip_handles=True,
                               reduce_len=True)
    tweet_tokens = tokenizer.tokenize(tweet)

    tweets_clean = []
    for word in tweet_tokens:
        if (word not in stopwords_english and  # remove stopwords
            word not in string.punctuation):  # remove punctuation
            # tweets_clean.append(word)
            stem_word = stemmer.stem(word)  # stemming word
            tweets_clean.append(stem_word)

    return tweets_clean


def get_dict(file_name):
    """
    This function returns the english to french dictionary given a file where the each column corresponds to a word.
    Check out the files this function takes in your workspace.
    """
    my_file = pd.read_csv(file_name, delimiter=' ')
    etof = {}  # the english to french dictionary to be returned
    for i in range(len(my_file)):
        # indexing into the rows.
        en = my_file.loc[i][0]
        fr = my_file.loc[i][1]
        etof[en] = fr

    return etof


def cosine_similarity(A, B):
    '''
    Input:
        A: a numpy array which corresponds to a word vector
        B: A numpy array which corresponds to a word vector
    Output:
        cos: numerical number representing the cosine similarity between A and B.
    '''
    # you have to set this variable to the true label.
    cos = -10
    dot = np.dot(A, B)
    norma = np.linalg.norm(A)
    normb = np.linalg.norm(B)
    cos = dot / (norma * normb)

    return cos

# Procedure to plot and arrows that represents vectors with pyplot
def plot_vectors(vectors, colors=['k', 'b', 'r', 'm', 'c'], axes=None, fname='image.svg', ax=None):
    scale = 1
    scale_units = 'x'
    x_dir = []
    y_dir = []
    
    for i, vec in enumerate(vectors):
        x_dir.append(vec[0][0])
        y_dir.append(vec[0][1])
    
    if ax == None:
        fig, ax2 = plt.subplots()
    else:
        ax2 = ax
      
    if axes == None:
        x_axis = 2 + np.max(np.abs(x_dir))
        y_axis = 2 + np.max(np.abs(y_dir))
    else:
        x_axis = axes[0]
        y_axis = axes[1]
        
    ax2.axis([-x_axis, x_axis, -y_axis, y_axis])
        
    for i, vec in enumerate(vectors):
        ax2.arrow(0, 0, vec[0][0], vec[0][1], head_width=0.05 * x_axis, head_length=0.05 * y_axis, fc=colors[i], ec=colors[i])
    
    if ax == None:
        plt.show()
        fig.savefig(fname)


In [8]:
from gensim.models import KeyedVectors

en_embeddings = KeyedVectors.load_word2vec_format('./GoogleNews-vectors-negative300.bin', binary = True)
fr_embeddings = KeyedVectors.load_word2vec_format('./wiki.multi.fr.vec')



# loading the english to french dictionaries
en_fr_train = get_dict('en-fr.train.txt')
print('The length of the english to french training dictionary is', len(en_fr_train))
en_fr_test = get_dict('en-fr.test.txt')
print('The length of the english to french test dictionary is', len(en_fr_train))

english_set = set(en_embeddings.vocab)
french_set = set(fr_embeddings.vocab)
en_embeddings_subset = {}
fr_embeddings_subset = {}
french_words = set(en_fr_train.values())

for en_word in en_fr_train.keys():
    fr_word = en_fr_train[en_word]
    if fr_word in french_set and en_word in english_set:
        en_embeddings_subset[en_word] = en_embeddings[en_word]
        fr_embeddings_subset[fr_word] = fr_embeddings[fr_word]


for en_word in en_fr_test.keys():
    fr_word = en_fr_test[en_word]
    if fr_word in french_set and en_word in english_set:
        en_embeddings_subset[en_word] = en_embeddings[en_word]
        fr_embeddings_subset[fr_word] = fr_embeddings[fr_word]


pickle.dump( en_embeddings_subset, open( "en_embeddings.p", "wb" ) )
pickle.dump( fr_embeddings_subset, open( "fr_embeddings.p", "wb" ) )

ImportError: cannot import name 'triu' from 'scipy.linalg' (C:\ProgramData\anaconda3\Lib\site-packages\scipy\linalg\__init__.py)

In [11]:
# en_fr = {
#     "the":  "le",
# "Ashgabat": "ashgabat",
# "the": "les",
# "the": "la",
# "and": "et",
# "was": "fut",
# "was": "etait",
# "was": "était",
# }

# en_embeddings = {
#     "the": [0.2, 0.3, 0.4, 0.5],
#     "Ashgabat": [0.4444, 0.213, 0.14, 0.5],
#     "the": [0.4444, 0.0000213, 0.00014, 0.5120],
#     "the": [0.44004004, 0.000913, 0.01484, 0.145],
#     "and": [0.42144, 0.28413, 0.70014, 0.0005],
#     "was": [0.0004, 0.00023, 0.00007, 0.0006],
#     "was": [0.0008, 0.00063, 0.00001, 0.0056],
#     "was": [0.0098, 0.00763, 0.08001, 0.0756],
# }

# fr_embeddings = {
#     "le": [0.27, 0.0013, 0.1204, 0.125],
#     "ashgabat": [0.0044, 0.1213, 0.014, 0.05],
#     "les": [0.0145, 0.0213, 0.0084, 0.20],
#     "la": [0.004, 0.000913, 0.01484, 0.145],
#     "et": [0.74, 0.13, 0.7, 0.05],
#     "fut": [0.4, 0.23, 0.07, 0.06],
#     "etait": [0.8, 0.63, 0.701, 0.0056],
#     "était": [0.9, 0.763, 0.81, 0.756],
# }

In [41]:
n_cols = 4

def get_matrices(en_fr, en_embeddings, fr_embeddings):
    X = np.empty((0, n_cols))
    y = np.empty((0, n_cols))

    en_emb_set = set(en_embeddings.keys())
    fr_emb_set = set(fr_embeddings.keys())
    
    for en, fr in en_fr.items():
        if en in en_emb_set and fr in fr_emb_set:
            X_rows = np.array([en_embeddings[en]])
            y_rows = np.array([fr_embeddings[fr]])
            X = np.append(X, X_rows, axis = 0)
            y = np.append(y, y_rows, axis = 0)
    return X, y

In [77]:
X, y = get_matrices(en_fr, en_embeddings, fr_embeddings)
y

array([[0.004   , 0.000913, 0.01484 , 0.145   ],
       [0.0044  , 0.1213  , 0.014   , 0.05    ],
       [0.74    , 0.13    , 0.7     , 0.05    ],
       [0.9     , 0.763   , 0.81    , 0.756   ]])

In [59]:
def compute_loss(X, Y, R):
    m = X.shape[0]
    y_pred = np.dot(X, R)
    A = y_pred - Y
    f_a = np.linalg.norm(A, 'fro') ** 2
    return f_a / m

In [62]:
R = np.random.rand(4, 4)
compute_loss(X, y, R)

1.5876522214232947

In [67]:
def compute_gradient(X, Y, R):
    m = X.shape[0]
    
    emd_pred = np.dot(X, R)
    diff = emd_pred - Y
    grad = (2 / m) * np.dot(X.T, diff)
    return grad

In [68]:
compute_gradient(X, y, R)

array([[ 0.2344706 ,  0.40319767,  0.21835551,  0.35856566],
       [ 0.05409672,  0.19154266,  0.06034815,  0.19563832],
       [-0.05005214,  0.34156598, -0.01701724,  0.32127527],
       [ 0.21040403,  0.14660296,  0.18725503,  0.16921253]])

In [72]:
def align_embeddings(X, Y, train_steps = 100, lr = 0.0003):
    np.random.seed(129)
    R = np.random.rand(X.shape[1], X.shape[1])
    
    for step in range(train_steps):
        if step % 25 == 0:
            print(f"Training Loss at EPOCH {step} ==> {compute_loss(X, Y, R)}")
            
        gradient = compute_gradient(X, Y, R)

        R -= lr * gradient
    return R

In [76]:
# testing
np.random.seed(129)
m = 10
n = 5
X_test = np.random.rand(m, n)
Y_test = np.random.rand(m, n) * 0.1

R = align_embeddings(X_test, Y_test, train_steps = 10000, lr = 0.0003)
R

Training Loss at EPOCH 0 ==> 3.7241601261682264
Training Loss at EPOCH 25 ==> 3.628289198210136
Training Loss at EPOCH 50 ==> 3.53497687566553
Training Loss at EPOCH 75 ==> 3.4441545620485563
Training Loss at EPOCH 100 ==> 3.3557555012458273
Training Loss at EPOCH 125 ==> 3.2697147281352903
Training Loss at EPOCH 150 ==> 3.185969020530152
Training Loss at EPOCH 175 ==> 3.104456852412266
Training Loss at EPOCH 200 ==> 3.025118348420393
Training Loss at EPOCH 225 ==> 2.9478952395596627
Training Loss at EPOCH 250 ==> 2.8727308200994743
Training Loss at EPOCH 275 ==> 2.799569905627937
Training Loss at EPOCH 300 ==> 2.7283587922318246
Training Loss at EPOCH 325 ==> 2.659045216771834
Training Loss at EPOCH 350 ==> 2.591578318223778
Training Loss at EPOCH 375 ==> 2.5259086000570807
Training Loss at EPOCH 400 ==> 2.461987893622769
Training Loss at EPOCH 425 ==> 2.3997693225238583
Training Loss at EPOCH 450 ==> 2.339207267941771
Training Loss at EPOCH 475 ==> 2.280257334893146
Training Loss at 

array([[ 0.15470112, -0.12114165,  0.17425389, -0.05234771,  0.36958048],
       [-0.00751705,  0.20129935, -0.07709541, -0.10961917, -0.1403363 ],
       [ 0.23015578, -0.40786196, -0.0575964 ,  0.0784273 , -0.06366766],
       [-0.14405517,  0.36661322,  0.08600006,  0.44312352,  0.14785688],
       [-0.14722985,  0.15661418,  0.04303335, -0.16227744, -0.07008161]])

In [78]:
R_train = align_embeddings(X, y, train_steps = 10000, lr = 0.0003)

Training Loss at EPOCH 0 ==> 0.8938798305862191
Training Loss at EPOCH 25 ==> 0.8922999292030824
Training Loss at EPOCH 50 ==> 0.8907315077416809
Training Loss at EPOCH 75 ==> 0.8891744740819633
Training Loss at EPOCH 100 ==> 0.8876287368636618
Training Loss at EPOCH 125 ==> 0.8860942054799766
Training Loss at EPOCH 150 ==> 0.8845707900713128
Training Loss at EPOCH 175 ==> 0.8830584015190684
Training Loss at EPOCH 200 ==> 0.8815569514394757
Training Loss at EPOCH 225 ==> 0.8800663521774932
Training Loss at EPOCH 250 ==> 0.8785865168007492
Training Loss at EPOCH 275 ==> 0.8771173590935331
Training Loss at EPOCH 300 ==> 0.8756587935508412
Training Loss at EPOCH 325 ==> 0.874210735372468
Training Loss at EPOCH 350 ==> 0.8727731004571496
Training Loss at EPOCH 375 ==> 0.8713458053967533
Training Loss at EPOCH 400 ==> 0.8699287674705188
Training Loss at EPOCH 425 ==> 0.8685219046393445
Training Loss at EPOCH 450 ==> 0.8671251355401218
Training Loss at EPOCH 475 ==> 0.865738379480119
Trainin

In [79]:
def cosine(a, b):
    dotptoduct = np.dot(a, b)
    norm_dot = np.dot(np.linalg.norm(a), np.linalg.norm(b))
    cosine = dotptoduct / norm_dot
    return cosine

In [80]:
def nearest_neighbor(v, candidates, k = 1):
    similarities = []
    for c in candidates:
        sim = cosine(v, c)
        similarities.append(sim)

    sorted_sim = np.argsort(similarities)
    k_idx = sorted_sim[-k:]
    return k_idx

In [81]:
v = np.array([1, 0, 1])
candidates = np.array([[1, 0, 5], [-2, 5, 3], [2, 0, 1], [6, -9, 5], [9, 9, 9]])
print(candidates[nearest_neighbor(v, candidates, 3)])

[[9 9 9]
 [1 0 5]
 [2 0 1]]


In [86]:
def test_vocab(X, Y, R):
    k_idx = 0
    pred = np.dot(X, R)
    correct = 0
    print(pred)
    
    for i in range(len(pred)):
        pred_idx = nearest_neighbor(pred[i][:], Y, 1)
        print(i, pred_idx)

        if pred_idx == i:
            correct += 1

    accuracy = correct / X.shape[0]
    return accuracy

In [87]:
test_vocab(X, y, R_train)

[[0.12137843 0.06099942 0.07097218 0.05846171]
 [0.322052   0.26806939 0.28787949 0.15107235]
 [0.58393494 0.13825389 0.71333143 0.08430615]
 [0.0257261  0.02825108 0.05530665 0.0211075 ]]
0 [3]
1 [3]
2 [2]
3 [3]


0.5

In [90]:
# get the positive and negative tweets
all_positive_tweets = twitter_samples.strings('positive_tweets.json')
all_negative_tweets = twitter_samples.strings('negative_tweets.json')
all_tweets = all_positive_tweets + all_negative_tweets

In [92]:
def get_document_embedding(tweet, en_embedding):
    doc_embedding = np.zeros(300)
    processed_doc = process_tweet(tweet)
    for word in processed_doc:
        doc_embedding += en_embedding.get(word, 0)
    return doc_embedding

In [96]:
custom_tweet = "RT @Twitter @chapagain Hello There! Have a great day. :) #good #morning http://chapagain.com.np"
tweet_embedding = get_document_embedding(custom_tweet, en_embeddings)
tweet_embedding[:5]

array([0., 0., 0., 0., 0.])

In [144]:
def get_document_vecs(all_docs, en_embeddings):
    ind2doc_dict = {}
    doc_vec_l = []
    for i, doc in enumerate(all_docs):
        doc_emb = get_document_embedding(doc, en_embeddings)
        ind2doc_dict[i] = doc_emb
        doc_vec_l.append(doc_emb)
    doc_vec_matrix = np.vstack(doc_vec_l)
    return doc_vec_matrix, ind2doc_dict

In [145]:
document_vecs, ind2Tweet = get_document_vecs(all_tweets, en_embeddings)

In [146]:
print(len(ind2Tweet))
print(document_vecs.shape)

10000
(10000, 300)


In [147]:
tweet = "I'm sad"
processed = process_tweet(tweet)
tweet_embedding = get_document_embedding(tweet, en_embeddings)

In [148]:
idx = np.argmax(cosine(document_vecs, tweet_embedding))
print(all_tweets[idx])

#FollowFriday @France_Inte @PKuchly57 @Milipol_Paris for being top engaged members in my community this week :)


C:\Users\Administrator\AppData\Local\Temp\ipykernel_5964\3365568139.py:4: RuntimeWarning: invalid value encountered in divide
  cosine = dotptoduct / norm_dot


In [150]:
# The number of planes. We use log2(625) to have ~16 vectors/bucket.
N_PLANES = 10
# Number of times to repeat the hashing to improve the search.
N_UNIVERSES = 25

N_VECS = len(all_tweets)       # This many vectors.
N_DIMS = len(ind2Tweet[1])     # Vector dimensionality.
print(f"Number of vectors is {N_VECS} and each has {N_DIMS} dimensions.")

Number of vectors is 10000 and each has 300 dimensions.


In [151]:
np.random.seed(0)
planes_l = [np.random.normal(size=(N_DIMS, N_PLANES))
            for _ in range(N_UNIVERSES)]
planes_l[0].shape

(300, 10)

In [152]:
def hash_value_of_vector(v, planes):
    # step 1: dot product between the vector and the planes matrix
    dotproduct = np.dot(v, planes)
    # get the sign of each value
    sign_of_dotproduct = np.sign(dotproduct)
    # determine which sides each value belongs
    h = np.where(sign_of_dotproduct > 0, 1, 0)
    h = np.squeeze(h)
    
    
    hash_value = 0
    n_planes = planes.shape[1]
    for i in range(n_planes):
        hash_value += 2 ** i * h[i]

    return int(hash_value)

In [153]:
np.random.seed(0)
idx = 0
planes = planes_l[idx]
v = np.random.rand(1, 300)
hash_value = hash_value_of_vector(v, planes)
print(f"Hash value for the vector is {hash_value}")

Hash value for the vector is 768


In [156]:
def make_hash_table(vecs, planes):
    n_planes = planes.shape[1]
    n_buckets = 2 ** n_planes
    
    hash_table = {i: [] for i in range(n_buckets)}
    id_table = {i: [] for i in range(n_buckets)}
    
    for i, v in enumerate(vecs):
        h_value = hash_value_of_vector(v, planes)
        
        hash_table[h_value].append(v)
        id_table[h_value].append(i)
        
    return hash_table, id_table

In [157]:
np.random.seed(0)
planes = planes_l[0]
vec = np.random.rand(1, 300)
tmp_hash_table, tmp_id_table = make_hash_table(document_vecs, planes)

print(f"The hash table at key 0 has {len(tmp_hash_table[0])} document vectors")
print(f"The id table at key 0 has {len(tmp_id_table[0])}")
print(f"The first 5 document indices stored at key 0 of are {tmp_id_table[0][0:5]}")

The hash table at key 0 has 10000 document vectors
The id table at key 0 has 10000
The first 5 document indices stored at key 0 of are [0, 1, 2, 3, 4]


In [158]:
hash_tables = []
id_tables = []

for u in range(N_UNIVERSES):
    print(f"We are working on Univgerse #{u}")
    planes = planes_l[u]
    hash_table, id_table = make_hash_table(document_vecs, planes)
    hash_tables.append(hash_table)
    id_tables.append(id_table)



We are working on Univgerse #0
We are working on Univgerse #1
We are working on Univgerse #2
We are working on Univgerse #3
We are working on Univgerse #4
We are working on Univgerse #5
We are working on Univgerse #6
We are working on Univgerse #7
We are working on Univgerse #8
We are working on Univgerse #9
We are working on Univgerse #10
We are working on Univgerse #11
We are working on Univgerse #12
We are working on Univgerse #13
We are working on Univgerse #14
We are working on Univgerse #15
We are working on Univgerse #16
We are working on Univgerse #17
We are working on Univgerse #18
We are working on Univgerse #19
We are working on Univgerse #20
We are working on Univgerse #21
We are working on Univgerse #22
We are working on Univgerse #23
We are working on Univgerse #24


In [163]:
def approximate_knn(doc_id, v, planes_l, k = 1, num_universe = N_UNIVERSES):
    vecs_to_consider_l = list()
    ids_to_consider_l = list()
    ids_to_consider_set = set()

    
    for u in range(num_universe):
        planes = planes_l[u]
        h_value = hash_value_of_vector(v, planes)
        h_table = hash_tables[u]
        document_vectors_l = hash_table[h_value]
        id_table = id_tables[u]
        new_ids_to_consider = id_table[h_value]
        
        if doc_id in new_ids_to_consider:
            new_ids_to_consider.remove(doc_id)
            print(f"removed doc_id {doc_id} of input vector from new_ids_to_search")
        
        for i, new_id in enumerate(new_ids_to_consider):
            if new_id not in ids_to_consider_set:
                doc_vec_at_i = document_vectors_l[i]
                vecs_to_consider_l.append(doc_vec_at_i)
                ids_to_consider_l.append(new_id)
                ids_to_consider_set.add(new_id)
                
    print("Fast considering %d vecs" % len(vecs_to_consider_l))
    
    # convert the vecs to consider set to a list, then to a numpy array
    vecs_to_consider_arr = np.array(vecs_to_consider_l)
    
    # call nearest neighbors on the reduced list of candidate vectors
    nearest_neighbor_idx_l = nearest_neighbor(v, vecs_to_consider_arr, k=k)
    
    # Use the nearest neighbor index list as indices into the ids to consider
    # create a list of nearest neighbors by the document ids
    nearest_neighbor_ids = [ids_to_consider_l[idx]
                            for idx in nearest_neighbor_idx_l]
    
    return nearest_neighbor_ids

In [164]:
#document_vecs, ind2Tweet
doc_id = 0
doc_to_search = all_tweets[doc_id]
vec_to_search = document_vecs[doc_id]

In [167]:
nearest_neighbor_ids = approximate_knn(
    doc_id, vec_to_search, planes_l, 3, 5)

removed doc_id 0 of input vector from new_ids_to_search
removed doc_id 0 of input vector from new_ids_to_search
removed doc_id 0 of input vector from new_ids_to_search
removed doc_id 0 of input vector from new_ids_to_search
removed doc_id 0 of input vector from new_ids_to_search
Fast considering 9999 vecs


C:\Users\Administrator\AppData\Local\Temp\ipykernel_5964\3365568139.py:4: RuntimeWarning: invalid value encountered in scalar divide
  cosine = dotptoduct / norm_dot


In [168]:
print(f"Nearest neighbors for document {doc_id}")
print(f"Document contents: {doc_to_search}")
print("")

for neighbor_id in nearest_neighbor_ids:
    print(f"Nearest neighbor at document id {neighbor_id}")
    print(f"document contents: {all_tweets[neighbor_id]}")

Nearest neighbors for document 0
Document contents: #FollowFriday @France_Inte @PKuchly57 @Milipol_Paris for being top engaged members in my community this week :)

Nearest neighbor at document id 3337
document contents: Photo: randy9bis: Beautiful physique, shaved, uncut, and a tattoo: sexy boi !  :-) http://t.co/XcWxo5jVVY
Nearest neighbor at document id 3330
document contents: @Twytterina indeed! :)
Nearest neighbor at document id 9999
document contents: @eawoman As a Hull supporter I am expecting a misserable few weeks :-(
